spring.application.name=F38-Advance-Mapping
spring.datasource.url=jdbc:mysql://localhost:3306/f38-advance-mapping
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true