spring.application.name=F38-Security
spring.datasource.url=jdbc:mysql://localhost:3306/f38-security
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true