spring.application.name=Product-Micro
spring.datasource.url=jdbc:mysql://localhost:3306/Product
spring.datasource.username=root
spring.datasource.password=password

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
server.port = 9090